baseURL = "https://eoinfarrell.dev/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hello"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy"]

[Author]
    name = "Eoin Farrell"

[params]

    [[params.author]]
        name = "Eoin Farrell"

    [params.colors]
        background = "#81c6ff"
        foreground = "#edf7ff"
        hover = "#ffba82"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:nope@eoinfarrell.dev"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "http://github.com/eoinfarrell"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/eoinfarrell239"

    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://www.linkedin.com/in/eoinfarrell/"

    [[params.links]]
        iconset = "fas"
        icon = "images"
        title = "Photos"
        url = "https://photos.eoinfarrell.dev"