name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli
    - name: Gatsby Build
      run: gatsby build
    - name: Change Directory
      run: |
        mkdir ../../EoinFarrell.github.io
        cd ../../EoinFarrell.github.io
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: EoinFarrell/EoinFarrell.github.io
    - name: Copy Build
      run: cp ../eoinfarrell.dev/eoinfarrell.dev/public .
    - name: Simple commit
      uses: zwaldowski/git-commit-action@v1
